package org.impactindiafoundation.iifllemeddocket.LLE_MedDocket_ROOM_DATABASE.ROOM_DATABASE_MODEL

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "Eye_Pre_Op_Notes")
data class Eye_Pre_Op_Notes(
    @PrimaryKey(autoGenerate = true) val _id: Int,
    val camp_id: Int,
    val createdDate: String,
    val eye_pre_op_admission_date: String,
    val eye_pre_op_alprax: String,
    val eye_pre_op_amlodipine: String,
    val eye_pre_op_antibiotic: String,
    val eye_pre_op_antibiotic_detail: String,
    val eye_pre_op_antibiotic_other: String,
    val eye_pre_op_antibiotic_result: String,
    val eye_pre_op_antihyp: String,
    val eye_pre_op_antihyp_detail: String,
    val eye_pre_op_betadine: String,
    val eye_pre_op_bp_diastolic: String,
    val eye_pre_op_bp_interpretation: String,
    val eye_pre_op_bp_systolic: String,
    val eye_pre_op_bs_f: String,
    val eye_pre_op_bs_pp: String,
    val eye_pre_op_bt: String,
    val eye_pre_op_cbc: String,
    val eye_pre_op_ciplox: String,
    val eye_pre_op_ciplox_drop: String,
    val eye_pre_op_ct: String,
    val eye_pre_op_dia: String,
    val eye_pre_op_dia_detail: String,
    val eye_pre_op_diamox: String,
    val eye_pre_op_discussed_with: String,
    val eye_pre_op_discussed_with_detail: String,
    val eye_pre_op_ecg: String,
    val eye_pre_op_flur_eye: String,
    val eye_pre_op_haemoglobin: String,
    val eye_pre_op_hbsag: String,
    val eye_pre_op_hcv: String,
    val eye_pre_op_head_bath: String,
    val eye_pre_op_heart: String,
    val eye_pre_op_heart_detail: String,
    val eye_pre_op_heart_rate: String,
    val eye_pre_op_historyof: String,
    val eye_pre_op_hiv: String,
    val eye_pre_op_identify_eye: String,
    val eye_pre_op_iol_power: String,
    val eye_pre_op_nil_mouth: String,
    val eye_pre_op_notes: String,
    val eye_pre_op_o2_saturation: String,
    val eye_pre_op_o2_saturation_interpretation: String,
    val eye_pre_op_other: String,
    val eye_pre_op_other_detail: String,
    val eye_pre_op_plain_tropical: String,
    val eye_pre_op_pt: String,
    val eye_pre_op_recommendation: String,
    val eye_pre_op_recommendation_detail: String,
    val eye_pre_op_symptoms: String,
    val eye_pre_op_temp: String,
    val eye_pre_op_temp_unit: String,
    val eye_pre_op_tropical_drop: String,
    val eye_pre_op_tropicamide: String,
    val eye_pre_op_wash_face: String,
    val eye_pre_op_xylocaine: String,
    val eye_pre_op_xylocaine_detail: String,
    val eye_pre_op_xylocaine_other: String,
    val eye_pre_op_xylocaine_result: String,
    val patient_id: Int,
    val user_id: String,
    val eyePreOpNotesImagepath:String,
    val image_type:String,
    val isSyn: Int =0
)




