package org.impactindiafoundation.iifllemeddocket.LLE_MedDocket_ROOM_DATABASE.ROOM_DATABASE_MODEL

import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "Eye_Post_Op_AND_Follow_ups")
data class Eye_Post_Op_AND_Follow_ups(
    @PrimaryKey(autoGenerate = true)val _id: Int,
    val camp_id: Int,
    val createdDate: String,
    val eye_post_op_2nd_date: String,
    val eye_post_op_3rd_date: String,
    val eye_post_op_addi_detail_left: String,
    val eye_post_op_addi_detail_right: String,
    val eye_post_op_asses_imedi: String,
    val eye_post_op_assess_catract: String,
    val eye_post_op_assess_catract_detail: String,
    val eye_post_op_bp: String,
    val eye_post_op_check_pupil: String,
    val eye_post_op_check_pupil_detail: String,
    val eye_post_op_cifloxacin: String,
    val eye_post_op_cifloxacin_detail: String,
    val eye_post_op_counseling: String,
    val eye_post_op_diclofenac: String,
    val eye_post_op_diclofenac_detail: String,
    val eye_post_op_dimox: String,
    val eye_post_op_dimox_detail: String,
    val eye_post_op_discharge_check: String,
    val eye_post_op_distant_vision_left: String,
    val eye_post_op_distant_vision_right: String,
    val eye_post_op_distant_vision_unit_left: String,
    val eye_post_op_distant_vision_unit_right: String,
    val eye_post_op_early_post_op: String,
    val eye_post_op_ed_homide: String,
    val eye_post_op_ed_homide_detail: String,
    val eye_post_op_eye_1: String,
    val eye_post_op_eye_1_detail: String,
    val eye_post_op_eye_2: String,
    val eye_post_op_eye_2_detail: String,
    val eye_post_op_eye_3: String,
    val eye_post_op_eye_3_detail: String,
    val eye_post_op_eye_4: String,
    val eye_post_op_eye_4_detail: String,
    val eye_post_op_eye_5: String,
    val eye_post_op_eye_5_detail: String,
    val eye_post_op_fundus_exam: String,
    val eye_post_op_fundus_pathology: String,
    val eye_post_op_head_position: String,
    val eye_post_op_homide: String,
    val eye_post_op_homide_detail: String,
    val eye_post_op_hypersol: String,
    val eye_post_op_hypersol_detail: String,
    val eye_post_op_last_date: String,
    val eye_post_op_location_centration: String,
    val eye_post_op_lubricant: String,
    val eye_post_op_lubricant_detail: String,
    val eye_post_op_moxifloxacin: String,
    val eye_post_op_moxifloxacin_detail: String,
    val eye_post_op_near_vision_left: String,
    val eye_post_op_near_vision_right: String,
    val eye_post_op_other: String,
    val eye_post_op_other_detail: String,
    val eye_post_op_pantaprezol: String,
    val eye_post_op_pantaprezol_detail: String,
    val eye_post_op_pr: String,
    val eye_post_op_pressure_regular: String,
    val eye_post_op_rr: String,
    val eye_post_op_slit_lamp_exam: String,
    val eye_post_op_temp: String,
    val eye_post_op_temp_unit: String,
    val eye_post_op_timolol: String,
    val eye_post_op_timolol_detail: String,
    val eye_post_op_w_addi_detail_left: String,
    val eye_post_op_w_addi_detail_right: String,
    val eye_post_op_w_distant_vision_left: String,
    val eye_post_op_w_distant_vision_right: String,
    val eye_post_op_w_distant_vision_unit_left: String,
    val eye_post_op_w_distant_vision_unit_right: String,
    val eye_post_op_w_near_vision_left: String,
    val eye_post_op_w_near_vision_right: String,
    val eye_post_op_w_pinhole_improve_left: String,
    val eye_post_op_w_pinhole_improve_right: String,
    val eye_post_op_w_pinhole_improve_unit_left: String,
    val eye_post_op_w_pinhole_improve_unit_right: String,
    val eye_post_op_w_pinhole_left: String,
    val eye_post_op_w_pinhole_right: String,
    val patient_id: Int,
    val userId: String,
    val isSyn: Int =0
)
